# Generated by Django 3.2.18 on 2023-03-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='producer',
            new_name='director',
        ),
    ]
